### ISSUE TITLE
New API in latest version

### ISSUE THREAD

**Issue by darwineee** [chRyNaN/navigation#7]
I have upgraded this library to the 0.8.0 version. Now the API StackDuplicateContentStrategy is gone. I don't know how to clear my stack before navigate to a specific destination. Please help!!

**Comment by chRyNaN** [comment]
It has been moved to the constructor function of the `Navigator` and renamed `NavigationStrategy.DuplicateDestination`:
https://github.com/chRyNaN/navigation/blob/develop/navigation-core/src/commonMain/kotlin/com.chrynan.navigation/Navigator.kt#L175

You can also provide it to the remember navigator functions. The previous design was too complex because it would change based on the call site, but this manipulates the internal stack, creating a lot of issues. So it was moved to the constructor so that it is consistent for every operation.

**Comment by darwineee** [comment]
Thank you!
